server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zuoer_home?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot


knife4j:
  enable: true
  openapi:
    title: zuoer小程序接口
    description:
    email: 240635165@qq.com
    concat: xm
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      admin:
        group-name: 后台管理接口
        api-rule: package
        api-rule-resources:
          - com.zuoer.homeManager.controller.admin
      mini:
        group-name: 小程序接口
        api-rule: package
        api-rule-resources:
          - com.zuoer.homeManager.controller.mini