spring:
  profiles:
    ## 指定服务名称，在nacos中的名字
    active: dev

knife4j:
  enable: true
  openapi:
    title: zuoer api
    description:
    email: 240635165@qq.com
    concat: xm
    url: https://docs.xiaominfo.com
    version: v4.0
    license: Apache 2.0
    license-url: https://stackoverflow.com/
    terms-of-service-url: https://stackoverflow.com/
    group:
      admin:
        group-name: admin
        api-rule: package
        api-rule-resources:
          - com.zuoer.controller.admin
      mini:
        group-name: wechat
        api-rule: package
        api-rule-resources:
          - com.zuoer.controller.mini